name: etherpad-lite
version: master
vendor: Alexander Sack <asac@ubuntu.com>
summary: a collaborative text editing webservice in node.js
description: This example is not really production quality
icon: icon.png

binaries:
  server-cli:
    exec: runpad
    description: etherpad-lite cli binary

services:
  server:
    start: runpad
    description: etherpad-lite service

parts:
  etherpad-lite:
    plugin: nodejs
    node-packages: ['src/']
    source: git://github.com/asac/etherpad-lite.git
    source-tag: run-npm-install
  wrapper:
    plugin: copy
    files:
      runpad: runpad
  topintegration:
    plugin: make
    source: .
